DROP DATABASE IF EXISTS responsi2;
CREATE DATABASE responsi2;

USE responsi2;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    bio TEXT NOT NULL
);
